# Generated by Django 4.1.4 on 2022-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_group_created_by_alter_membership_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groupchats',
            field=models.ManyToManyField(through='chat.Membership', to='chat.group'),
        ),
    ]
