# Generated by Django 4.1.4 on 2022-12-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_by',
        ),
    ]
