# Generated by Django 4.1.4 on 2022-12-30 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_group_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groupchats',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='chat.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
