# Generated by Django 4.1.4 on 2022-12-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_membership_group_alter_membership_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
